services:
  api:
    build:
      context: .
      dockerfile: docker/api/local/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=sqs,dynamodb
      - DEFAULT_REGION=us-east-1
      - PERSISTENCE=1
      - DEBUG=1
    volumes:
      - "./localstack:/home/localstack/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
