services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: -jar DynamoDBLocal.jar -sharedDb -inMemory
  
  api:
    build:
      context: .
      dockerfile: docker/api/local/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
