services:
  api:
    build:
      context: .
      dockerfile: docker/api/local/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/ping"]
      interval: 30s
      timeout: 20s
      retries: 5
    restart: always
    environment:
      - MYSQL_HOST=${MYSQL_HOST:-mysql}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-root}
      - MYSQL_DBNAME=${MYSQL_DBNAME:-go_mail}
      - MYSQL_SSL_MODE=${MYSQL_SSL_MODE:-disable}
      - MYSQL_TIMEZONE=${MYSQL_TIMEZONE:-UTC}
      - MYSQL_MAX_IDLE_CONNS=${MYSQL_MAX_IDLE_CONNS:-10}
      - MYSQL_MAX_OPEN_CONNS=${MYSQL_MAX_OPEN_CONNS:-100}
      - MYSQL_CONN_MAX_LIFETIME=${MYSQL_CONN_MAX_LIFETIME:-1h}

  mysql:
    image: mysql/mysql-server:8.0
    container_name: gomail-mysql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=go_mail
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - TZ=UTC
    volumes:
      - mysql-db-main:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot"]
      interval: 3s
      timeout: 10s
      retries: 20

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT

  control-center:
    image: confluentinc/cp-enterprise-control-center:6.0.1
    hostname: control-center
    depends_on:
      - kafka
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_CONNECT_CLUSTER: http://kafka-connect:8083
      PORT: 9021

volumes:
  mysql-db-main:
